version: '3'
services:
  db:
    image: postgres:10.4
    ports:
      -"4000"
  web:
    build: .
    volumes:
      - .:/app
    ports:
      -4000:4000
    links:
      - db
    depends_on:
      - db
    environment:
      - TWOCENTS_HOST=https://two-cents.1bleacherreport.com
      - POSTGRES_USERNAME=msampaga
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOSTNAME=db
      - MIX_ENV=dev
