version: '3'
services:
  db:
    image: postgres:10.4
    ports:
      - "5432"
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 4000:4000
    environment:
      - POSTGRES_USERNAME=msampaga
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOSTNAME=db
      - MIX_ENV=dev
