version: '3'
services:
  db:
    image: postgres:10.4
    ports:
      - "5432"
  web:
    build: .
    environment:
      - TWOCENTS_HOST=http://two-cents.1bleacherreport.com/
      - POSTGRES_USERNAME=msampaga
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOSTNAME=db
      - MIX_ENV=dev
